### ISSUE TITLE
Unable to post animated gif or mp4: "422 Error processing thumbnail for uploaded media"

### ISSUE THREAD

**Issue by annatech** [it-objects/terraform-aws-terra3#39]
I discovered and have been trying to resolved for the past couple months a strange issue which prevents users from posting animated gifs to my Mastodon instance. 

Current behavior:
- User clicks on paperclip icon to attach an animated gif to a post
- The media item uploads and the post windows indicates that it is uploading and then processing
- After about 28.5 seconds, the upload stalls and throws the following error:
-- "422 Error processing thumbnail for uploaded media"
- After that, the page needs to be reloaded before the attachment action can work again.

Expected behavior:
- User clicks on paperclip icon to attach an animated gif to a post
- The media item uploads and the post windows indicates that it is uploading and then processing (xhr calls complete successfully)
- A thumbnail of the gif (which has been converted to an .mp4 file in the background) appears and is ready for posting

Investigation:
I noticed that, during this event, Sidekiq reports the following retry action:
- Queue: default
- Job: PostProcessMediaWorker
- Arguments: %id_of_media%
- Error: 
(example)
``
Errno::ENOENT: No such file or directory @ rb_sysopen - /opt/mastodon/public/system/media_attachments/files/110/888/339/885/320/433/original/e4b9cc41c743c791.mp4
``

NOTE:
My instance is configured to work with S3 and CloudFront, as defined in the Terraform configuration.
- I modified the domain_name to launch the Mastodon instance with the domain_name, rather than solution_name.domain_name.

The processed gif file appears as an mp4, successfully, with the correct S3 directory path.
Example:
``/media_attachments/files/110/888/339/885/320/433/original/e4b9cc41c743c791.mp4
``

So far, I have been unable to identify WHY Sidekiq fails with a reference to a missing local file, when the instance is otherwise correctly configured to store and serve media via S3 + CloudFront.

UPDATE: I modified the title to include that mp4 attachments present the same behavior with failed media processing.

**Comment by w13k** [comment]
Thanks for the detailed issue description, @annatech. And very interesting to read, that you've been running the instance successfully for some months already. The Terra3 examples are currently not our main focus and out of my head I have no idea what the reason of this issue could be, besides trying to update to the latest container images. But I assume that you are on the latest Mastodon version. I hope we or someone else will find some time in the near future to have a more closer look into it.

**Comment by annatech** [comment]
Thank you for sharing your Terraform work with the community @w13k . Your terraform-aws-terra3 project has helped me launch a Mastodon site for a client as well as build & deploy a new "Autobot" project I am working on (extensible multi-bot container written in PHP), all as a single Terraform Cloud Plan. 

Aside from a few fixes related to CloudFront configuration and running under a domain.tld address (rather than subdomain.domain.tld), everything else has been stable, even through upgrades up to 4.1.6.

In the meantime, I've been hesitant to reach out to the main Mastodon Github Issues community until I can confirm I didn't break something :)  

Next, I am considering cloning the latest Mastodon repo to modify and test a few changes to the Paperclip classes which might help resolve (or simply avoid) the issue I am experiencing with media processing. 

I will post an update if the problem turns out to be an S3 / CloudFront variables configuration issue.

Thanks!

**Comment by annatech** [comment]
No further action needed at this time. I will continue research on this issue and share any relevant information with @w13k .
